agent_id = "24d3b6a1-dede-44a5-b75e-cf1b00860591"
server = "https://cloudpub.ru/"
token = "i4YG0zayOhhbGmkpHSQBq6sOtZ7qTxKdhuz2WyHLvuk"
heartbeat_timeout = 40
minimize_to_tray_on_close = true
minimize_to_tray_on_start = false

[transport]
type = "websocket"

[transport.tcp]

[transport.tls]

[transport.websocket]
tls = true
