agent_id = "226fb666-cc78-4336-9a54-0404f6193c16"
server = "https://cloudpub.ru/"
token = "dpiaF-CPEc715LNkLUl8Ga5EsfqLIP6Zt8_rXYxbmDE"
heartbeat_timeout = 40
minimize_to_tray_on_close = true
minimize_to_tray_on_start = false

[transport]
type = "websocket"

[transport.tcp]

[transport.tls]

[transport.websocket]
tls = true
